### ISSUE TITLE
Fix "delete account" flow

### ISSUE THREAD

**Issue by chriscarrollsmith** [Promptly-Technologies-LLC/fastapi-jinja2-postgres-webapp#11]
Currently the delete_account endpoint returns a successful redirect response, but it doesn't successfully either delete or log out the current user.

**Comment by AkanshuS** [comment]
Logout and then delete from the session.

**Comment by chriscarrollsmith** [comment]
https://github.com/Promptly-Technologies-LLC/fastapi-jinja2-postgres-webapp/pull/48 will close this issue when approved.
